version: '3.8'
services:

  localsecret:
    build:
      context: ./dockerbuilds
      dockerfile: Dockerfile.secret
    image: localsecret
    container_name: ls-patched
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
      - 8090:9090
    networks:
      - akashathon

  gaia-node:
    image: gaia-node:latest
    container_name: gaia-node
    volumes:
      - data:/opt/gaia/data
    ports:
      - 1316:1317
      - 16657:26657
      - 16656:26656
      - 9090:9090
    environment:
      - BINARY=gaiad
      - CHAINID=test-2
      - STAKEDENOM=uatom
      - ALLOW_ICA_EXEC=yes
      - RUN_BACKGROUND=0
    networks:
      - akashathon

  hermes:
    image: hermes:1.3.0-a285c01
    depends_on:
      - "localsecret"
      - "gaia-node"
    networks:
      - akashathon

volumes:
  data:
    name: akashathon-data
    external: false

networks:
  akashathon:
    name: akashathon
    external: false
