const SECRET_MNEMONIC = import.meta.env.SECRET_MNEMONIC;
const SECRET_CHAIN_ENDPOINT = import.meta.env.SECRET_CHAIN_ENDPOINT;
const SECRET_CHAIN_ID = import.meta.env.SECRET_CHAIN_ID;
const SECRET_TOKEN = import.meta.env.SECRET_TOKEN;

const CONSUMER_MNEMONIC = import.meta.env.CONSUMER_MNEMONIC || SECRET_MNEMONIC;
const CONSUMER_CHAIN_ENDPOINT = import.meta.env.CONSUMER_CHAIN_ENDPOINT;
const CONSUMER_CHAIN_ID = import.meta.env.CONSUMER_CHAIN_ID;
const CONSUMER_TOKEN = import.meta.env.CONSUMER_TOKEN;



export {
    SECRET_MNEMONIC,
    SECRET_CHAIN_ENDPOINT,
    SECRET_CHAIN_ID,
    SECRET_TOKEN,
    CONSUMER_MNEMONIC,
    CONSUMER_CHAIN_ENDPOINT,
    CONSUMER_CHAIN_ID,
    CONSUMER_TOKEN
};