const SECRET_MNEMONIC = import.meta.env.SECRET_MNEMONIC;
const CONSUMER_MNEMONIC = import.meta.env.CONSUMER_MNEMONIC || SECRET_MNEMONIC;

const SECRET_CHAIN_ENDPOINT = import.meta.env.SECRET_CHAIN_ENDPOINT;
const CONSUMER_CHAIN_ENDPOINT = import.meta.env.CONSUMER_CHAIN_ENDPOINT;


export {
    SECRET_MNEMONIC,
    CONSUMER_MNEMONIC,
    SECRET_CHAIN_ENDPOINT,
    CONSUMER_CHAIN_ENDPOINT
};